ANTIBOT/urls.py
from django.urls import path
from .views import Console

app_name = "ANTIBOT"

urlpatterns = [
    path('console/', Console.render, name='console'),
    path('run/', Console.run, name='run'),
    path('stop/', Console.stop, name='stop'),
    path('clear/', Console.clear, name='clear'),
    path('set/<str:value>', Console.set, name='set'),
    path('error/', Console.error, name='error'),
    path('webhook/', Console.webhook, name='webhook')
]

ChatGPT/urls.py
from django.urls import path
from .views import Console
from .views import *

app_name = "ChatGPT"

urlpatterns = [
    path('console/', Console.render, name='console'),
    path('run/', Console.run, name='run'),
    path('stop/', Console.stop, name='stop'),
    path('clear/', Console.clear, name='clear'),
    path('set/<str:value>', Console.set, name='set'),
    path('error/', Console.error, name='error'),
    path('webhook/', Console.webhook, name='webhook')
]

TelegramBots/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from TelegramBots import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    path('chatgpt/', include('ChatGPT.urls')),
    path('antibot/', include('ANTIBOT.urls')),
]

ChatGPT/models.py
import json

from django.db import models


class GPTModels(models.Model):
    name = models.CharField(max_length=250, verbose_name="Название")
    slug = models.CharField(max_length=250, verbose_name="Slug")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Модель"
        verbose_name_plural = "Модели"


class TelegramUsers(models.Model):
    id = models.BigIntegerField(primary_key=True, null=False, unique=True, verbose_name="ID пользователя")
    username = models.CharField(null=True, blank=True, max_length=250, verbose_name="Имя пользователя")
    first_name = models.CharField(null=True, blank=True, max_length=250, verbose_name="Имя")
    last_name = models.CharField(null=True, blank=True, max_length=250, verbose_name="Фамилия")
    blocked = models.BooleanField(default=False, verbose_name="Заблокирован")
    is_staff = models.BooleanField(default=False, verbose_name="Персонал")
    RPD = models.IntegerField(verbose_name="Количество ежедневных запросов")
    RPD_BONUS = models.IntegerField(verbose_name="Количество бонусных запросов")
    IPD = models.IntegerField(verbose_name="Количество ежедневных изображений")
    referrer = models.ForeignKey('self',
                                 on_delete=models.CASCADE,
                                 null=True,
                                 blank=True,
                                 verbose_name="Реферер")
    referrals = models.IntegerField(verbose_name="Количество рефералов")
    messages = models.TextField(default='[]', verbose_name="Сообщения")
    model = models.ForeignKey(GPTModels, on_delete=models.CASCADE, verbose_name="Модель")

    def set_rpd(self, quantity):
        self.RPD = quantity
        self.save()

    def set_rpd_bonus(self, quantity):
        self.RPD_BONUS = quantity
        self.save()

    def set_ipd(self, quantity):
        self.IPD = quantity
        self.save()

    def set_referrer(self, referrer):
        self.referrer = referrer
        self.save()

    def set_model(self, model):
        self.model = model
        self.save()

    def get_rpd(self):
        return self.RPD

    def get_rpd_bonus(self):
        return self.RPD_BONUS

    def get_ipd(self):
        return self.IPD

    def get_referral(self):
        return self.referrals

    def get_referrer(self):
        return self.referrer

    def get_messages(self):
        messages = json.loads(self.messages)
        return messages

    def get_model(self):
        return self.model

    def clear_messages(self):
        self.messages = '[]'
        self.save()

    def remove_rpd(self, quantity):
        self.RPD -= quantity
        self.save()

    def remove_rpd_bonus(self, quantity):
        self.RPD_BONUS -= quantity
        self.save()

    def remove_ipd(self, quantity):
        self.IPD -= quantity
        self.save()

    def add_rpd(self, quantity):
        self.RPD += quantity
        self.save()

    def add_rpd_bonus(self, quantity):
        self.RPD_BONUS += quantity
        self.save()

    def add_ipd(self, quantity):
        self.IPD += quantity
        self.save()

    def add_referral(self):
        self.referrals += 1
        self.save()

    def add_message(self, role, content):
        messages = json.loads(self.messages)
        messages.append({"role": role, "content": content})
        self.messages = json.dumps(messages)
        self.save()

    def ban(self):
        self.blocked = True
        self.save()

    def unban(self):
        self.blocked = False
        self.save()

    def is_blocked(self):
        return self.blocked

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"


class Promocodes(models.Model):
    code = models.CharField(max_length=16, verbose_name="Код")
    NOR = models.IntegerField(verbose_name="Количество запросов")

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = "Промокод"
        verbose_name_plural = "Промокоды"


class Channels(models.Model):
    id = models.BigIntegerField(verbose_name="ID канала", primary_key=True)
    name = models.CharField(max_length=250, verbose_name="Название канала")
    url = models.URLField()

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = "Канал"
        verbose_name_plural = "Каналы"


class Prices(models.Model):
    description = models.CharField(max_length=250, verbose_name="Описание")
    price = models.IntegerField(verbose_name="Цена")
    value = models.IntegerField(verbose_name="Количество")
    top = models.BooleanField(default=False, verbose_name="В топе")

    def __str__(self):
        return self.description

    def in_top(self):
        return self.top

    class Meta:
        verbose_name = "Цена"
        verbose_name_plural = "Цены"


class Tips(models.Model):
    amount = models.IntegerField(verbose_name="Количество")

    def __str__(self):
        return str(self.amount)

    class Meta:
        verbose_name = "Чаевые"
        verbose_name_plural = "Чаевые"

ChatGPT/views.py
import inspect
import json
import os
import subprocess
import threading
import logging
import time
import traceback

import pymysql
import telebot
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from django.db import transaction
from django.contrib.sites.models import Site
from django.shortcuts import render, redirect
from openai import OpenAI, RateLimitError
from pymysql.cursors import DictCursor
from telebot import types
from telebot.types import BotCommand, LabeledPrice
from dotenv import load_dotenv
from telegram import constants
from telegram.helpers import escape_markdown

from TelegramBots import settings
from ChatGPT.models import TelegramUsers, Promocodes, Channels, GPTModels, Prices, Tips

load_dotenv()

logger = logging.getLogger('django')

try:
    URL = Site.objects.get_current().domain + "/chatgpt"
except Exception as e:
    URL = "https://example.com/chatgpt"
    logger.error(e)

WEBHOOK_URL = URL + "/webhook/"

TOKEN = os.getenv("TOKEN_CHATGPT")
API_KEY = os.getenv("API_KEY_CHATGPT")

Bot = telebot.TeleBot(TOKEN)

client = OpenAI(api_key=API_KEY)

commands = [
    BotCommand('start', '🔄 Запустить/перезапустить бота'),
    BotCommand('ref', "📨 Приглашение"),
    BotCommand('promocode', "🔑 Ввести промокод"),
    BotCommand('start_new_dialog', "➕ Начать новый диалог"),
]

Bot.set_my_commands(commands)


def requires_staff(func):
    def wrapper(request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.user.is_staff:
                return func(request, *args, **kwargs)

        return redirect(f'{reverse("admin:login")}?next={request.path}')

    return wrapper


class Console:
    botThread = None

    @staticmethod
    def set_webhook():
        Bot.remove_webhook()
        time.sleep(5)
        print(WEBHOOK_URL)
        Bot.set_webhook(url=WEBHOOK_URL)

    @staticmethod
    @csrf_exempt
    def webhook(request):
        if request.method == "POST":
            json_string = request.body.decode("utf-8")
            update = telebot.types.Update.de_json(json_string)
            Bot.process_new_updates([update])
            return JsonResponse({"status": "ok"})

    @staticmethod
    def status():
        is_bot = Bot.get_me().is_bot
        name = Bot.get_me().username

        text = f"Bot({name}) is bot: {is_bot}\n"
        return text

    @staticmethod
    @requires_staff
    def run(request):
        if Console.botThread is not None:
            if not Console.botThread.is_alive():
                Console.botThread = threading.Thread(target=Console.set_webhook())
                Console.botThread.start()
        else:
            Console.botThread = threading.Thread(target=Console.set_webhook())
            Console.botThread.start()
        print(f'Bot is now running in a separate thread.')
        return redirect('ChatGPT:console')

    @staticmethod
    @requires_staff
    def stop(request):
        if Console.botThread is not None:
            if Console.botThread.is_alive():
                Bot.delete_webhook()
        print(f'Bot is now stopping in a separate thread.')
        return redirect('ChatGPT:console')

    @staticmethod
    def run_command(value, command):
        if value == 'terminal':
            result = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, shell=True)
            return str(result.stdout), str(result.stderr)
        if value == 'mysql':
            try:
                with pymysql.connect(
                        host=settings.DB_HOST,
                        user=settings.DB_USER,
                        password=settings.DB_PASSWORD,
                        database=settings.DB_NAME,
                        charset='utf8mb4',
                        cursorclass=DictCursor
                ) as connection:
                    with connection.cursor() as cursor:
                        cursor.execute(command)

                        result = cursor.fetchall()

                        result = '\n'.join(str(item) for item in result)
                        return str(result), None
            except pymysql.Error as ex:
                return None, str(ex)
            except Exception as ex:
                return None, str(ex)

    @staticmethod
    @requires_staff
    def clear(request):
        request.session['command_history'] = []
        request.session.modified = True
        return redirect('ChatGPT:console')

    @staticmethod
    @requires_staff
    def set(request, value):
        request.session['command_line'] = value
        return redirect('ChatGPT:console')

    @staticmethod
    @requires_staff
    def render(request):
        name = Bot.get_my_name().name
        context = {
            'bot_name': name
        }
        if 'command_line' not in request.session:
            request.session['command_line'] = 'terminal'

        if request.method == 'POST':
            command = request.POST.get('command')
            stdout, stderr = Console.run_command(request.session['command_line'], command)
            # сохраняем историю выполнения команд в сессии
            if 'command_history' not in request.session:
                request.session['command_history'] = []

            request.session['command_history'].append({
                'command': command,
                'stdout': stdout,
                'stderr': stderr,
            })
            request.session.modified = True

        return render(request, 'chatgpt/console.html', context)

    @staticmethod
    def error(request):
        return render(request, 'chatgpt/error.html')


def requires_subscription(func):
    @Bot.callback_query_handler(func=lambda call: call.data == 'check_subscribe')
    @transaction.atomic
    def wrapper(message, *args, **kwargs):
        try:
            with pymysql.connect(
                    host=settings.DB_HOST,
                    user=settings.DB_USER,
                    password=settings.DB_PASSWORD,
                    database=settings.DB_NAME,
                    charset='utf8mb4',
                    cursorclass=DictCursor
            ) as connection:
                connection.ping(reconnect=True)

                if not TelegramUsers.objects.filter(id=message.from_user.id).exists():
                    user = TelegramUsers(
                        id=message.from_user.id,
                        username=message.from_user.username,
                        first_name=message.from_user.first_name,
                        last_name=message.from_user.last_name,
                        blocked=False,
                        is_staff=False,
                        RPD=5,
                        RPD_BONUS=0,
                        IPD=1,
                        referrer=None,
                        referrals=0,
                        messages='[]',
                        model=GPTModels.objects.get(name="GPT-4")
                    )
                    user.save()
                    time.sleep(1)

                user = TelegramUsers.objects.get(id=message.from_user.id)
                if user.is_blocked():
                    Bot.send_message(message.from_user.id,
                                     "‼️Вы заблокированы ‼️\n"
                                     "За подробностями писать @FynnFu")
                    return None

                reply_message_id = None
                if type(message) == types.Message:
                    reply_message_id = message.message_id
                elif type(message) == types.CallbackQuery:
                    reply_message_id = message.message.message_id

                validation = True
                channels = Channels.objects.all()
                markup = types.InlineKeyboardMarkup()

                for channel in channels:
                    chat_member = Bot.get_chat_member(channel.id, message.from_user.id)
                    if not (chat_member.status == "member" or
                            chat_member.status == "administrator" or
                            chat_member.status == "creator"):
                        validation = False
                        markup.add(
                            types.InlineKeyboardButton(text=channel.name, url=channel.url)
                        )

                markup.add(
                    types.InlineKeyboardButton(text="✅ Я подписался", callback_data='check_subscribe')
                )

                if validation:
                    return func(message, *args, **kwargs)
                else:
                    if type(message) == types.CallbackQuery:
                        if message.data == 'check_subscribe':
                            Bot.answer_callback_query(callback_query_id=message.id,
                                                      show_alert=True,
                                                      text='Подпишитесь на все каналы!')
                        else:
                            Bot.send_message(message.from_user.id,
                                             "Для того, чтобы пользоваться ботом, вам необходимо подписаться на "
                                             "канал.\n"
                                             "После подписки, нажмите на соответствующую кнопку.",
                                             reply_markup=markup,
                                             reply_to_message_id=reply_message_id)
                    else:
                        Bot.send_message(message.from_user.id,
                                         "Для того, чтобы пользоваться ботом, вам необходимо подписаться на канал.\n"
                                         "После подписки, нажмите на соответствующую кнопку.",
                                         reply_markup=markup,
                                         reply_to_message_id=reply_message_id)
                    return None
        except Exception as ex:

ChatGPT/templates/chatgpt/console.html
{% extends 'admin/base_site.html' %}
{% load static %}
{% block title %}
    {{ bot_name }} Console
{% endblock %}
{% block extrastyle %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        .cli {
            color: white;
        }
        .colM {
            height: 100% !important;
            overflow: hidden !important;
        }
        #footer {
            display: none;
        }
        #container {
            overflow: hidden;
            background-color: black;
        }
    </style>
{% endblock %}
{% block breadcrumbs %}
    <div class="breadcrumbs">
        <a href="{% url 'ChatGPT:console' %}">
            <h3>{{ bot_name }} Console ({{ request.session.command_line }})</h3>
        </a>
        {% block breadcrumb %}{% endblock %}
    </div>
{% endblock %}
{% block content %}
    <div class="cli d-flex flex-row w-100" style="height: 100%; max-width: 100%;">
        <div class="w-75">
            <div class="w-100 overflow-auto pr-5" style="max-height: 70vh; height: 100%">
                {% if request.session.command_history %}
                    <ol>
                        {% for history_item in request.session.command_history %}
                            <li>
                                <strong>{{ history_item.command }}</strong><br>
                                {% if history_item.stdout %}
                                    <pre class="success">{{ history_item.stdout }}</pre>
                                {% endif %}
                                {% if history_item.stderr %}
                                    <pre class="error">{{ history_item.stderr }}</pre>
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ol>
                {% else %}
                    <p>История команд пуста.</p>
                {% endif %}
            </div>
            <form method="post">
                {% csrf_token %}
                <input class="w-75" type="text" name="command" id="command" required>
                <button type="submit" class="btn btn-success w-auto">Отправить</button>
            </form>
        </div>
        <div class="w-25 d-flex flex-column">
            <a href="{% url 'ChatGPT:run' %}" class="mt-2 mb-2">
                <button class="btn btn-success w-100 p-2">Запуск бота</button>
            </a>
            <a href="{% url 'ChatGPT:stop' %}" class="mt-2 mb-2">
                <button class="btn btn-danger w-100 p-2">Остановить бота</button>
            </a>
            <a href="{% url 'ChatGPT:clear' %}" class="mt-2 mb-2">
                <button class="btn btn-warning w-100 p-2">Очистить терминал</button>
            </a>
            <a href="{% url 'ChatGPT:set' 'terminal' %}" class="mt-2 mb-2">
                <button class="btn btn-primary w-100 p-2">Terminal</button>
            </a>
            <a href="{% url 'ChatGPT:set' 'mysql' %}" class="mt-2 mb-2">
                <button class="btn btn-primary w-100 p-2">MySQL</button>
            </a>
            <a href="{% url 'ChatGPT:error' %}" class="mt-2 mb-2" target="_blank">
                <button class="btn btn-info w-100 p-2">Страница ошибки</button>
            </a>
        </div>
    </div>
{% endblock %}

ChatGPT/templates/chatgpt/error.html
Traceback (most recent call last):
  File "/Users/fynnfu/PycharmProjects/TelegramBots/ChatGPT/views.py", line 579, in generate_gpt_response
    completion = client.chat.completions.create(
  File "/Users/fynnfu/PycharmProjects/TelegramBots/venv/lib/python3.10/site-packages/openai/_utils/_utils.py", line 299, in wrapper
    return func(*args, **kwargs)
  File "/Users/fynnfu/PycharmProjects/TelegramBots/venv/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 594, in create
    return self._post(
  File "/Users/fynnfu/PycharmProjects/TelegramBots/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1055, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/Users/fynnfu/PycharmProjects/TelegramBots/venv/lib/python3.10/site-packages/openai/_base_client.py", line 834, in request
    return self._request(
  File "/Users/fynnfu/PycharmProjects/TelegramBots/venv/lib/python3.10/site-packages/openai/_base_client.py", line 865, in _request
    return self._retry_request(
  File "/Users/fynnfu/PycharmProjects/TelegramBots/venv/lib/python3.10/site-packages/openai/_base_client.py", line 925, in _retry_request
    return self._request(
  File "/Users/fynnfu/PycharmProjects/TelegramBots/venv/lib/python3.10/site-packages/openai/_base_client.py", line 865, in _request
    return self._retry_request(
  File "/Users/fynnfu/PycharmProjects/TelegramBots/venv/lib/python3.10/site-packages/openai/_base_client.py", line 925, in _retry_request
    return self._request(
  File "/Users/fynnfu/PycharmProjects/TelegramBots/venv/lib/python3.10/site-packages/openai/_base_client.py", line 877, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}