ANTIBOT/urls.py
from django.urls import path
from .views import Console

app_name = "ANTIBOT"

urlpatterns = [
    path('console/', Console.render, name='console'),
    path('run/', Console.run, name='run'),
    path('stop/', Console.stop, name='stop'),
    path('clear/', Console.clear, name='clear'),
    path('set/<str:value>', Console.set, name='set'),
    path('error/', Console.error, name='error'),
    path('webhook/', Console.webhook, name='webhook')
]

TelegramBots/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from TelegramBots import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    path('chatgpt/', include('ChatGPT.urls')),
    path('antibot/', include('ANTIBOT.urls')),
]

ANTIBOT/models.py
from django.db import models


# Create your models here.
class TelegramUsers(models.Model):
    id = models.BigIntegerField(primary_key=True, null=False, unique=True, verbose_name="ID пользователя")
    username = models.CharField(null=True, blank=True, max_length=250, verbose_name="Имя пользователя")
    first_name = models.CharField(null=True, blank=True, max_length=250, verbose_name="Имя")
    last_name = models.CharField(null=True, blank=True, max_length=250, verbose_name="Фамилия")
    blocked = models.BooleanField(default=False, verbose_name="Заблокирован")
    is_staff = models.BooleanField(default=False, verbose_name="Персонал")

    def ban(self):
        self.blocked = True
        self.save()

    def unban(self):
        self.blocked = False
        self.save()

    def is_blocked(self):
        return self.blocked

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"


class Channels(models.Model):
    id = models.IntegerField(primary_key=True, verbose_name='ID канала')
    name = models.CharField(max_length=250, verbose_name='Имя канала')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Канал"
        verbose_name_plural = "Каналы"

ANTIBOT/views.py
import inspect
import logging
import os
import subprocess
import threading
import time
import traceback

import pymysql
import telebot
from django.contrib.sites.models import Site
from django.db import transaction
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from dotenv import load_dotenv
from pymysql.cursors import DictCursor
from telebot import types
from telebot.apihelper import ApiTelegramException
from telebot.types import InlineKeyboardMarkup, InlineKeyboardButton

from ANTIBOT.models import TelegramUsers, Channels
from TelegramBots import settings

load_dotenv()

logger = logging.getLogger('django')

try:
    URL = Site.objects.get_current().domain + "/antibot"
except Exception as e:
    URL = "https://example.com/antibot"
    logger.error(e)

WEBHOOK_URL = URL + "/webhook/"

TOKEN = os.getenv("TOKEN_ANTIBOT")

Bot = telebot.TeleBot(TOKEN)

CHANNEL_ID = -1002033981480


def requires_staff(func):
    def wrapper(request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.user.is_staff:
                return func(request, *args, **kwargs)

        return redirect(f'{reverse("admin:login")}?next={request.path}')

    return wrapper


class Console:
    botThread = None

    @staticmethod
    def set_webhook():
        Bot.remove_webhook()
        time.sleep(5)
        Bot.set_webhook(url=WEBHOOK_URL)

    @staticmethod
    @csrf_exempt
    def webhook(request):
        if request.method == "POST":
            json_string = request.body.decode("utf-8")
            update = telebot.types.Update.de_json(json_string)
            Bot.process_new_updates([update])
            return JsonResponse({"status": "ok"})

    @staticmethod
    @requires_staff
    def run(request):
        if Console.botThread is not None:
            if not Console.botThread.is_alive():
                Console.botThread = threading.Thread(target=Console.set_webhook())
                Console.botThread.start()
        else:
            Console.botThread = threading.Thread(target=Console.set_webhook())
            Console.botThread.start()
        print(f'Bot is now running in a separate thread.')
        return redirect('ANTIBOT:console')

    @staticmethod
    @requires_staff
    def stop(request):
        if Console.botThread is not None:
            if Console.botThread.is_alive():
                Bot.delete_webhook()
        print(f'Bot is now stopping in a separate thread.')
        return redirect('ANTIBOT:console')

    @staticmethod
    def run_command(value, command):
        if value == 'terminal':
            result = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, shell=True)
            return str(result.stdout), str(result.stderr)
        if value == 'mysql':
            try:
                with pymysql.connect(
                        host=settings.DB_HOST,
                        user=settings.DB_USER,
                        password=settings.DB_PASSWORD,
                        database=settings.DB_NAME,
                        charset='utf8mb4',
                        cursorclass=DictCursor
                ) as connection:
                    with connection.cursor() as cursor:
                        cursor.execute(command)

                        result = cursor.fetchall()

                        result = '\n'.join(str(item) for item in result)
                        return str(result), None
            except pymysql.Error as ex:
                return None, str(ex)
            except Exception as ex:
                return None, str(ex)

    @staticmethod
    @requires_staff
    def clear(request):
        request.session['command_history'] = []
        request.session.modified = True
        return redirect('ANTIBOT:console')

    @staticmethod
    @requires_staff
    def set(request, value):
        request.session['command_line'] = value
        return redirect('ANTIBOT:console')

    @staticmethod
    @requires_staff
    def render(request):
        name = Bot.get_my_name().name
        context = {
            'bot_name': name
        }
        if 'command_line' not in request.session:
            request.session['command_line'] = 'terminal'

        if request.method == 'POST':
            command = request.POST.get('command')
            stdout, stderr = Console.run_command(request.session['command_line'], command)
            # сохраняем историю выполнения команд в сессии
            if 'command_history' not in request.session:
                request.session['command_history'] = []

            request.session['command_history'].append({
                'command': command,
                'stdout': stdout,
                'stderr': stderr,
            })
            request.session.modified = True

        return render(request, 'antibot/console.html', context)

    @staticmethod
    def error(request):
        return render(request, 'antibot/error.html')


@Bot.chat_join_request_handler()
def approve_request(message):
    msg = f"Привет! Я ANTIBOT система.\n" \
          f"\n" \
          f"Для одобрения заявки, пройди капчу:"
    keyboard = InlineKeyboardMarkup()
    button = InlineKeyboardButton(text="Я человек 👤", callback_data='success')
    keyboard.add(button)
    try:
        Bot.send_message(message.from_user.id, msg, reply_markup=keyboard)
    except ApiTelegramException as ex:
        send_error_for_admins(message, ex, inspect.currentframe().f_code.co_name, traceback.format_exc())


@Bot.callback_query_handler(func=lambda call: call.data == 'success')
@transaction.atomic
def success(call):
    try:
        with pymysql.connect(
                host=settings.DB_HOST,
                user=settings.DB_USER,
                password=settings.DB_PASSWORD,
                database=settings.DB_NAME,
                charset='utf8mb4',
                cursorclass=DictCursor
        ) as connection:
            connection.ping(reconnect=True)

            if not TelegramUsers.objects.filter(id=call.from_user.id).exists():
                user = TelegramUsers(
                    id=call.from_user.id,
                    username=call.from_user.username,
                    first_name=call.from_user.first_name,
                    last_name=call.from_user.last_name,
                    blocked=False,
                    is_staff=False
                )
                user.save()
                time.sleep(1)

        try:
            Bot.approve_chat_join_request(CHANNEL_ID, call.from_user.id)
            Bot.edit_message_text(chat_id=call.from_user.id,
                                  message_id=call.message.message_id,
                                  text="✅ Капча пройдена, вы добавлены в канал",
                                  reply_markup=None)
        except ApiTelegramException as ex:
            if "USER_ALREADY_PARTICIPANT" in str(ex):
                Bot.edit_message_text(chat_id=call.from_user.id,
                                      message_id=call.message.message_id,
                                      text="✅ Вы уже в канале",
                                      reply_markup=None)
            if "HIDE_REQUESTER_MISSING" in str(ex):
                Bot.edit_message_text(chat_id=call.from_user.id,
                                      message_id=call.message.message_id,
                                      text="❌ Приглашение не найдено, подайте заявку еще раз",
                                      reply_markup=None)
    except ApiTelegramException as ex:
        send_error_for_admins(call, ex, inspect.currentframe().f_code.co_name, traceback.format_exc())


def send_error_for_admins(message, ex, method_name, error_details):
    user_id = None
    if message is not None:
        Bot.send_message(message.from_user.id,
                         "⚠️ Произошла непредвиденная ошибка, сообщение об ошибке уже отправлено модерации.\n"
                         "Подождите пару минут и повторите попытку.")
        user_id = message.from_user.id
    text_to_error_html(error_details)
    admins = TelegramUsers.objects.filter(is_staff=True)
    text = "❗️ Сообщение от системы ❗️\n" \
           f"User ID: {user_id}\n" \
           f"Method: {method_name}\n" \
           f"Error type: {type(ex).__name__}\n" \
           f"Error message: {str(ex)}\n"
    logger.error(text)
    markup = types.InlineKeyboardMarkup()
    markup.add(
        types.InlineKeyboardButton(text="Страница с ошибкой", url=f"{URL}{reverse(f'ANTIBOT:error')}")
    )
    for admin in admins:
        Bot.send_message(admin.id, text, reply_markup=markup)


def text_to_error_html(error_details):
    try:
        app_templates_directory = os.path.join(settings.BASE_DIR, "ANTIBOT", 'templates')
        with open(app_templates_directory + "/antibot/error.html",
                  'w', encoding='utf-8') as file:
            file.write(str(error_details))
    except Exception as ex:
        logger.error(ex)

ANTIBOT/templates/antibot/console.html
{% extends 'admin/base_site.html' %}
{% load static %}
{% block title %}
    {{ bot_name }} Console
{% endblock %}
{% block extrastyle %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        .cli {
            color: white;
        }
        .colM {
            height: 100% !important;
            overflow: hidden !important;
        }
        #footer {
            display: none;
        }
        #container {
            overflow: hidden;
            background-color: black;
        }
    </style>
{% endblock %}
{% block breadcrumbs %}
    <div class="breadcrumbs">
        <a href="{% url 'ANTIBOT:console' %}">
            <h3>{{ bot_name }} Console ({{ request.session.command_line }})</h3>
        </a>
        {% block breadcrumb %}{% endblock %}
    </div>
{% endblock %}
{% block content %}
    <div class="cli d-flex flex-row w-100" style="height: 100%; max-width: 100%;">
        <div class="w-75">
            <div class="w-100 overflow-auto pr-5" style="max-height: 70vh; height: 100%">
                {% if request.session.command_history %}
                    <ol>
                        {% for history_item in request.session.command_history %}
                            <li>
                                <strong>{{ history_item.command }}</strong><br>
                                {% if history_item.stdout %}
                                    <pre class="success">{{ history_item.stdout }}</pre>
                                {% endif %}
                                {% if history_item.stderr %}
                                    <pre class="error">{{ history_item.stderr }}</pre>
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ol>
                {% else %}
                    <p>История команд пуста.</p>
                {% endif %}
            </div>
            <form method="post">
                {% csrf_token %}
                <input class="w-75" type="text" name="command" id="command" required>
                <button type="submit" class="btn btn-success w-auto">Отправить</button>
            </form>
        </div>
        <div class="w-25 d-flex flex-column">
            <a href="{% url 'ANTIBOT:run' %}" class="mt-2 mb-2">
                <button class="btn btn-success w-100 p-2">Запуск бота</button>
            </a>
            <a href="{% url 'ANTIBOT:stop' %}" class="mt-2 mb-2">
                <button class="btn btn-danger w-100 p-2">Остановить бота</button>
            </a>
            <a href="{% url 'ANTIBOT:clear' %}" class="mt-2 mb-2">
                <button class="btn btn-warning w-100 p-2">Очистить терминал</button>
            </a>
            <a href="{% url 'ANTIBOT:set' 'terminal' %}" class="mt-2 mb-2">
                <button class="btn btn-primary w-100 p-2">Terminal</button>
            </a>
            <a href="{% url 'ANTIBOT:set' 'mysql' %}" class="mt-2 mb-2">
                <button class="btn btn-primary w-100 p-2">MySQL</button>
            </a>
            <a href="{% url 'ANTIBOT:error' %}" class="mt-2 mb-2" target="_blank">
                <button class="btn btn-info w-100 p-2">Страница ошибки</button>
            </a>
        </div>
    </div>
{% endblock %}